### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by sneumann** [ToxBank/isa2rdf#6]
Please specify the license of this code. Check license compatibility in case parts of the codebase
were taken from other code (ignore the last bit if it was written from scratch). Thanks, Steffen

**Comment by sneumann** [comment]
Found LGPL3 on http://toxbank.github.io/isa2rdf/license.html
but a LICENSE file in the github would be great.

**Comment by vedina** [comment]
The pom.xml specifies the license.  

The http://toxbank.github.io/isa2rdf/license.html is generated via 

```
mvn site:site
```
